- hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('env', 'HOME') }}/.local/.npm-global/bin"
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    # Fix ubuntu
    git_projects: "/home/ubuntu/projects"
  pre_tasks:
    - name: Update the apt cache pre
      apt:
        update_cache: yes
      become: yes
      tags: 
        - node
        - zsh
        - install
        - neovim
        - core
        - pre
  tasks:
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/debugger.yml
    - import_tasks: fem_tasks/setup-user.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: fem_tasks/zsh.yml
    - import_tasks: fem_tasks/node.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: fem_tasks/git-projects.yml


# ubuntu-desktop