- name: Debug public key path
  debug:
    msg: "Public key path: {{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tags:
    - debugger

- name: List all public key files
  debug:
    var: item
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - debugger
    
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ ssh_source_key }}"
    dest: "{{ ssh_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ ssh_source_key }}.pub"
    dest: "{{ ssh_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: Display ssh path
  debug:
    msg: "{{ ssh_source_key }}"
  tags:
    - node
    - debugger
    - auth_codes

# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
