- name: Install zsh
  apt:
    name: zsh
    state: present
  tags:
    - zsh
- name: Install lolcat
  apt:
    name: lolcat
    state: present
  tags:
    - zsh

- name: Get the path of zsh
  ansible.builtin.set_fact:
    zsh_path: "{{ lookup('pipe', 'which zsh') }}"
  tags:
    - zsh
- name: Debug the zsh_path variable
  ansible.builtin.debug:
    msg: "zsh_path is {{ zsh_path }}"
  tags:
    - zsh

- name: Change the shell for the user
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ zsh_path }}"
  become: true
  tags:
    - zsh


# - name: Change shell
#   shell: sudo chsh -s 'which zsh'
#   become: true
#   tags:
#     - zsh
- name: Uninstall shell
  shell: rm -rf $HOME/.oh-my-zsh
  tags:
    - zsh


- name: Remove existing .oh-my-zsh directory if it exists
  ansible.builtin.file:
    path: $HOME/.oh-my-zsh
    state: absent
  become: true
  tags:
    - zsh

- name: Install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
  
- name: Install the zsh plugin autosuggestion
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' 
    dest: '$HOME/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - zsh
    - oh-my

- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  tags:
    - zsh
    - oh-my
