- name: Install zsh
  apt:
    name: zsh
    state: present
  tags:
    - zsh
- name: Install lolcat
  apt:
    name: lolcat
    state: present
  tags:
    - zsh
- name: Change shell
  shell: chsh -s 'which zsh'
  tags:
    - zsh
- name: Install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
- name: Install the zsh plugin autosuggestion
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' 
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - zsh
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  tags:
    - zsh